name: Bug Report
description: Report bugs based on the site.
labels: [bug]
body:
  - type: textarea
    attributes:
      label: Bug report
    validations:
      required: true

  - type: input
    attributes:
      label: Did you see anything wrong? If so, please mention it.
