name: Feature Request
description: No, i won't add extra key support, or the eplisey screen in furiosity, stop asking for it.
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: What things or features do you want to get added on the site?
    validations:
      required: true
